services:
  - type: worker
    name: encarbotscanner
    runtime: python
    envVars:
      - key: BOT_TOKEN
        value: "8219584179:AAEWSwq_Q52IjdHQc4rBrbQEOQiu3GqC4-Y"
      - key: CHAT_ID
        value: "5999882731"
    startCommand: "pythonÂ main.py"